In [1]:
import glob
import numpy as np
import cv2
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Dense, Flatten, Dropout

In [13]:
# Laden des Datensatzes
cur_path = "C:/Users/de136581/Documents/Uni/SoSe_2024/DSKI_Projekt/Data_trafic_Signs/GTSRB/"  
data = []
labels = []
classes = 43

Read ppm Datein into python

In [14]:
for i in range(classes):
    path = cur_path + 'Training/' + str(i).zfill(5) + '/*'
    images = glob.glob(path)
    for im in images:
        try:
            image = cv2.imread(im)
            image = cv2.resize(image, (30, 30))
            data.append(image)
            labels.append(i)
        except:
            print("Fehler beim Laden des Bildes")

data = np.array(data)
labels = np.array(labels)

Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim Laden des Bildes
Fehler beim La

In [4]:
print(data)

[[[[ 80  78  75]
   [ 78  76  74]
   [ 83  86  85]
   ...
   [ 74  74  68]
   [ 68  69  65]
   [ 66  67  66]]

  [[ 86  84  83]
   [ 82  80  80]
   [ 84  88  89]
   ...
   [ 78  77  73]
   [ 75  78  76]
   [ 78  80  80]]

  [[ 80  78  78]
   [ 86  85  86]
   [ 91  90  92]
   ...
   [ 72  74  72]
   [ 69  74  73]
   [ 74  78  78]]

  ...

  [[139 134 133]
   [132 127 123]
   [125 122 113]
   ...
   [ 89  94  94]
   [ 91  98  97]
   [ 99 103  99]]

  [[ 99  95  91]
   [103  98  91]
   [ 90  86  75]
   ...
   [ 96 102 104]
   [104 113 109]
   [ 98 104  96]]

  [[ 87  84  85]
   [106 100  95]
   [ 81  76  64]
   ...
   [ 95 102 102]
   [ 90 102  99]
   [ 89  97  90]]]


 [[[ 73  73  69]
   [ 79  79  76]
   [ 77  77  75]
   ...
   [ 80  81  76]
   [ 77  77  71]
   [ 70  68  66]]

  [[ 69  69  65]
   [ 76  76  74]
   [ 83  84  84]
   ...
   [ 89  83  90]
   [ 84  79  74]
   [ 73  69  67]]

  [[ 68  68  63]
   [ 72  72  71]
   [ 77  79  81]
   ...
   [ 91  86 105]
   [ 76  75  71]
   [ 69  71

In [15]:
# Train-Test-Aufteilung
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=42)

# One-Hot-Encoding der Labels
y_train = to_categorical(y_train, 43)
y_test = to_categorical(y_test, 43)

In [16]:
# Modellarchitektur
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu', input_shape=X_train.shape[1:]))
model.add(Conv2D(filters=32, kernel_size=(5, 5), activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(rate=0.25))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))

In [17]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [18]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10


ValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(32, 43), output.shape=(32, 9, 9, 64)

In [ ]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Genauigkeit: {test_acc:.4f}")

In [ ]:
predictions = model.predict(X_test)